# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: stiriAPI
  username: root
  password: Wireless123
  host: 127.0.0.1
  port: 3306
production:
  adapter: mysql2
  database: stiriAPI
  username: root
  password: Wireless123
  host: 127.0.0.1
  port: 3306
